apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.test.>
      requests:
        - curl --request POST --data
          '{"type":"TEST","event":"{{.type}}","text":"Test in {{.data.service}}
          and status {{.data.status}}"}'
          https://webhook.site/cc1ce4b8-fe9f-4b0d-a3e2-1b53ca7385ec
      subscriptionID: 479fb402-2f66-4f90-bc59-862fa10c51f7
    - type: sh.keptn.event.evaluation.finished
      requests:
        - curl --request POST --data
          '{"type":"EVALUATION","event":"{{.type}}","text":"Evaluation in
          {{.data.stage}} finished with result {{.data.result}}"}'
          https://webhook.site/cc1ce4b8-fe9f-4b0d-a3e2-1b53ca7385ec
      subscriptionID: 2868daa0-c9cb-4b68-bcb2-04cfab4a9d1f
