apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.evaluation.finished
      requests:
        - curl --request POST --data
          '{"type":"EVALUATION","event":"{{.type}}","text":"Stage =
          {{.data.stage}} finished with result = {{.data.result}}"}'
          https://webhook.site/cc1ce4b8-fe9f-4b0d-a3e2-1b53ca7385ec
      subscriptionID: 2868daa0-c9cb-4b68-bcb2-04cfab4a9d1f
    - type: sh.keptn.event.test.triggered
      sendFinished: false
      requests:
        - curl --request POST --data
          '{"type":"TEST-TRIGGERED","event":"{{.type}}","text":"Service =
          {{.data.service}} and status = {{.data.status}}"}'
          https://webhook.site/cc1ce4b8-fe9f-4b0d-a3e2-1b53ca7385ec
      subscriptionID: 479fb402-2f66-4f90-bc59-862fa10c51f7
    - type: sh.keptn.event.mytask.triggered
      sendFinished: false
      requests:
        - curl --request POST --data '{"event":"{{.type}}","text":"Service =
          {{.data.service}} and status = {{.data.status}}"}'
          https://webhook.site/cc1ce4b8-fe9f-4b0d-a3e2-1b53ca7385ec
    - type: sh.keptn.event.mytask.started
      requests:
        - curl --request POST --data '{"event":"{{.type}}","text":"In stage =
          {{.data.stage}}"}'
          https://webhook.site/cc1ce4b8-fe9f-4b0d-a3e2-1b53ca7385ec
      subscriptionID: 46be1f6e-77ad-4af6-b3ff-20b1ae80239d
